version: '3'

services:
  my-python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Adjust the port mapping as needed
    volumes:
      - .:/app  # Mount the current directory to /app in the container
